### ISSUE TITLE
Document Notifications - Conditions

### ISSUE THREAD

**Issue by jpettan** [The-Commit-Company/raven#1275]
Cannot save a document notification that has some conditions. Sample screenshot with error message.

<img width="1366" alt="Image" src="https://github.com/user-attachments/assets/0313ea62-f4b2-45af-9214-1ff53ffc54d9" />

**Comment by nikkothari22** [comment]
Hey @jpettan Can you check if you're on the latest version? I remember fixing this bug a few days ago.

**Comment by nikkothari22** [comment]
Never mind, this is a bug on the conditions. Found it.

**Comment by nikkothari22** [comment]
@jpettan This should be fixed now in the latest update

**Comment by nikkothari22** [comment]
@jpettan - can you tell me which DocType is this? I'll need to reproduce. I tried with expense claim and it worked.

**Comment by jpettan** [comment]
Payment Entry

<img width="1366" alt="Image" src="https://github.com/user-attachments/assets/d73217a3-5c1d-4f1a-a12e-28c692e77bdf" />

**Comment by nikkothari22** [comment]
@jpettan I was able to create a notification with the same condition on Payment Entry

<img width="1467" alt="Image" src="https://github.com/user-attachments/assets/d8a5a200-4692-4a76-a4d4-095da1350140" />

Maybe it's the quotes that are being used in the condition?

**Comment by jpettan** [comment]
Still the same for me. Not sure if it is environment specific. Using raven on iPad - Safari.

<img width="1366" alt="Image" src="https://github.com/user-attachments/assets/3f4de536-1b54-4c78-a96b-5f42dd6da209" />

**Comment by nikkothari22** [comment]
@jpettan It looks like the issue is with the quotes you're using to enclose "Receive"

**Comment by jpettan** [comment]
Thank you 🙏 

You guys are doing a fantastic job building an amazing product. 👏👏👏
