### ISSUE TITLE
Thread count doesn't get updated in real time.

### ISSUE THREAD

**Issue by iamejaaz** [The-Commit-Company/raven#1673]
If I add a message to the thread, the message count doesn't update in real time; it gets updated only after reloading the page.

![Image](https://github.com/user-attachments/assets/2dd46335-eccd-4bcc-84cb-eab968e72e11)

**Comment by nikkothari22** [comment]
This was fixed recently. Is the site on the latest version?

**Comment by iamejaaz** [comment]
> This was fixed recently. Is the site on the latest version?

@NagariaHussain 👉👈

**Comment by NagariaHussain** [comment]
Yup, it is on the latest comment.

**Comment by nikkothari22** [comment]
I just tested it on our site and it seems to work. @iamejaaz maybe it was a temporary socketIO issue? Can you check if you can reproduce it?

**Comment by iamejaaz** [comment]
No, @nikkothari22 , I'm still facing the issue. I created a thread and posted in it, but the thread count doesn’t update in real time.

**Comment by nikkothari22** [comment]
@iamejaaz Is this on the threads listing page, or on the channel where the original message is posted?

**Comment by iamejaaz** [comment]
> [@iamejaaz](https://github.com/iamejaaz) Is this on the threads listing page, or on the channel where the original message is posted?

On the channel @nikkothari22

**Comment by iamejaaz** [comment]
> Weird. I am unable to reproduce the bug at all.
> 
> I tried both ways - when I send a message vs someone else sends a message - in both cases the count was updating.

Hi @nikkothari22 ,

https://github.com/user-attachments/assets/d9f6546a-21a2-41f5-9491-bf459f3e80db

**Comment by nikkothari22** [comment]
Figured it out. So realtime events for unread messages and thread replies are published to the room "all" which is only broadcasted to "System Users". If the "Raven User" role does not have desk access, then this event is not broadcasted to those users. 

Possible options:
1. Either create a new room for Raven itself - not sure if that's possible in the custom socket handler in Frappe
2. Publish events to the "Raven Settings" doctype - and subscribe to that on the frontend.

**Comment by nikkothari22** [comment]
@iamejaaz That means even the unread message counts for channels were not working for you (and others who do not have access to the desk interface). Pushing a fix for this now.

**Comment by iamejaaz** [comment]
Thank you @nikkothari22 😀
